---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

tmp_dir: /tmp

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

nvm:
  path: /opt/nvm

zilliqa:
  validator:
    source_url: https://github.com/Zilliqa/zq2
    ports:
      p2p_port: 3333
      json_rpc_port: 4201
      api_port: 4202
  scilla:
    source_url: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-public/zq2
    ports:
      scilla_port: 3001
  statsagent:
    source_url: https://github.com/Zilliqa/eth-net-intelligence-api
