---
- name: Import setup_scilla playbook
  ansible.builtin.import_playbook: setup_scilla.yml

- name: Import setup_node playbook
  ansible.builtin.import_playbook: setup_node.yml

- name: Import setup_stats_agent playbook
  ansible.builtin.import_playbook: setup_stats_agent.yml
