---
- name: Set up Stats Agent
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
    - group_vars/default.yml
    - group_vars/{{ env }}.yml

  pre_tasks:
    - name: Setup Pre Tasks
      block:
        - name: Include environment setup tasks
          ansible.builtin.include_tasks: tasks/setup_environment.yml
          vars:
            type: statsagent

  tasks:
    - name: Run stats_agent role
      block:
        - name: Include common handlers
          ansible.builtin.include_role:
            name: common
        - name: Include stats_agent role
          ansible.builtin.include_role:
            name: stats_agent
