---
- name: Set up zilliqa node
  hosts: all
  become: true
  gather_facts: true
  vars:
    allowed_node_types: [validator]
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
    - group_vars/{{ env }}.yml

  pre_tasks:
    - name: Setup Pre Tasks
      when: type in allowed_node_types
      block:
        - name: Include environment setup tasks
          ansible.builtin.include_tasks: tasks/setup_environment.yml
        - name: Include dependencies setup tasks
          ansible.builtin.include_tasks: tasks/setup_dependencies.yml

  tasks:
    - name: Run node role
      when: type in allowed_node_types
      block:
        - name: Include common handlers
          ansible.builtin.include_role:
            name: common
        - name: Include node role
          ansible.builtin.include_role:
            name: node
