---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    zilliqa:
      hosts:
        validator.zilliqa.mainnet.encapsulate.xyz:
          type: validator
          scilla_lib_dir: /opt/zilliqa-scilla/lib
