---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    zilliqa:
      hosts:
        validator.zilliqa.mainnet.encapsulate.xyz:
          type: validator
