---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ sync_monitor_home_dir }}"
    directories: "{{ sync_monitor_directories }}"
    log_file_path: "{{ sync_monitor_log_file_path }}"

- name: Copy sync_monitor script
  ansible.builtin.template:
    src: sync_monitor.sh.j2
    dest: "{{ sync_monitor_script_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0755"

- name: Copy systemd service file
  ansible.builtin.template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ service_identifier }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service

- name: Copy timer service file
  ansible.builtin.template:
    src: systemd.timer.j2
    dest: "/etc/systemd/system/{{ service_identifier }}.timer"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart timer
