---
- name: Create scilla Docker container and copy binary
  vars:
    container_name: scilla
  block:
    - name: Create temporary scilla container for binary extraction
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ zilliqa.scilla.source_url }}:{{ zilliqa.scilla.version }}"
        state: present
        recreate: true
   
    - name: Copy scilla_http_server binary
      ansible.builtin.shell: >
        docker cp {{ container_name }}:/scilla/0/_build/default/src/runners/scilla_server_http.exe {{ scilla_bin_dir }}/{{ service_identifier }}
      args:
        executable: /bin/bash
      register: copy_result
      changed_when: copy_result.rc == 0
      failed_when:
        - copy_result.rc != 0
        - "'No such container' in copy_result.stderr"
      notify:
        - Restart service

    - name: Copy required libraries from container
      ansible.builtin.shell: |
        docker cp {{ container_name }}:/scilla/0/_build/default/vcpkg_installed/x64-linux-dynamic/lib/libcrypto.so.1.1 {{ scilla_lib_dir }}
        docker cp {{ container_name }}:/scilla/0/_build/default/vcpkg_installed/x64-linux-dynamic/lib/libssl.so.1.1 {{ scilla_lib_dir }}
        docker cp {{ container_name }}:/scilla/0/_build/default/vcpkg_installed/x64-linux-dynamic/lib/libCryptoUtils.so {{ scilla_lib_dir }}
        docker cp {{ container_name }}:/scilla/0/_build/default/vcpkg_installed/x64-linux-dynamic/lib/libSchnorr.so {{ scilla_lib_dir }}
        docker cp {{ container_name }}:/scilla/0/_build/default/vcpkg_installed/x64-linux-dynamic/lib/libcurl.so {{ scilla_lib_dir }}
        docker cp {{ container_name }}:/usr/lib/x86_64-linux-gnu/libev.so.4 {{ scilla_lib_dir }}
        docker cp {{ container_name }}:/usr/lib/x86_64-linux-gnu/libev.so.4.0.0 {{ scilla_lib_dir }}
      args:
        executable: /bin/bash
      register: copy_result
      changed_when: copy_result.rc == 0
      failed_when:
        - copy_result.rc != 0
        - "'No such container' in copy_result.stderr"
      notify:
        - Restart service
    
    - name: Ensure scilla_http_server binary has the correct permissions
      ansible.builtin.file:
        path: "{{ scilla_bin_dir }}/{{ service_identifier }}"
        owner: root
        group: root
        mode: "0755"

  always:
    - name: Remove scilla container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
