---
- name: Copy push metrics script
  ansible.builtin.template:
    src: push_metrics.sh.j2
    dest: "{{ stats_agent_push_metrics_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0755"

- name: Create cron job to push zilliqa metrics
  ansible.builtin.cron:
    name: "Push Zilliqa Metrics"
    minute: "*"
    hour: "*"
    job: "{{ stats_agent_push_metrics_file_path }}"
    user: root
