---
- name: Fetch checkpoint_block_num from the checkpoint URL
  ansible.builtin.uri:
    url: "{{ zilliqa.validator.checkpoint_url }}"
    return_content: true
  register: checkpoint_response

- name: Extract the checkpoint_block_num from the checkpoint_response
  ansible.builtin.set_fact:
    checkpoint_block_num: "{{ (checkpoint_response.content | regex_findall('[0-9]+\\.dat'))[0] }}"
  when: checkpoint_response.content is not none

- name: Convert checkpoint_block_num to hexadecimal
  ansible.builtin.set_fact:
    hex_value: "0x{{ '%X' | format(checkpoint_block_num | regex_replace('\\.dat$', '') | int) }}"

- name: Get checkpoint_block_num hash
  ansible.builtin.uri:
    url: "{{ zilliqa.validator.api_url }}"
    method: POST
    body_format: json
    body:
      method: "eth_getBlockByNumber"
      params: ["{{ hex_value }}", false]
      id: 1
      jsonrpc: "2.0"
    headers:
      Content-Type: "application/json"
  register: block_response

- name: Extract checkpoint_block_hash from response
  ansible.builtin.set_fact:
    checkpoint_block_hash: "{{ block_response.json.result.hash | regex_replace('^0x', '') }}"

- name: Stop service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: stopped

- name: Delete data folder
  ansible.builtin.file:
    path: "{{ sync_data_dir }}"
    state: absent

- name: Create data folder
  ansible.builtin.file:
    path: "{{ sync_data_dir }}"
    state: directory
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0755"

- name: Download the checkpoint snapshot file
  ansible.builtin.uri:
    url: "{{ zilliqa.validator.snapshot_url }}/{{ checkpoint_block_num }}"
    dest: "{{ sync_data_dir }}/{{ checkpoint_block_num }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"

- name: Update load_checkpoint configuration if commented
  replace:
    path: "{{ sync_config_file_path }}"
    regexp: '#\[nodes\.load_checkpoint\]\n#file = ""\n#hash = ""'
    replace: '[nodes.load_checkpoint]\nfile = "{{ sync_data_dir }}/{{ checkpoint_block_num }}"\nhash = "{{ checkpoint_block_hash }}"'

- name: Update load_checkpoint file path
  lineinfile:
    path: "{{ sync_config_file_path }}"
    regexp: '^file = ".*"$'
    line: 'file = "{{ sync_data_dir }}/{{ checkpoint_block_num }}"'
    insertafter: '^\[nodes\.load_checkpoint\]'

- name: Update load_checkpoint hash
  lineinfile:
    path: "{{ sync_config_file_path }}"
    regexp: '^hash = ".*"$'
    line: 'hash = "{{ checkpoint_block_hash }}"'
    insertafter: '^file = '

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: restarted
