---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ metrics_home_dir }}"
    directories: "{{ metrics_directories }}"
    log_file_path: "{{ metrics_log_file_path }}"

- name: Copy metrics script
  ansible.builtin.template:
    src: "metrics.sh.j2"
    dest: "{{ metrics_script_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0755"

- name: Copy metrics systemd service file
  ansible.builtin.template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ service_identifier }}.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service

- name: Copy metrics timer service file
  ansible.builtin.template:
    src: systemd.timer.j2
    dest: "/etc/systemd/system/{{ service_identifier }}.timer"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart timer
