---
dependencies:
  - role: morgangraphics.ansible-role-nvm
    nvm_version: "{{ nvm.version }}"
    nodejs_version: "{{ zilliqa.statsagent.node.version }}"
    nvm_dir: "{{ nvm.path }}"
    nvm_commands:
      - npm install -g pm2
